links:
 website: https://craftopoly.it
 discord: https://discord.com/gg/aaaaa
 telegram: https://t.me/craftopoly
 tiktok: https://tiktok.com/craftopoly

messages:
 follow_social: §a§lCRAFTOPOLY__§8▪ §7Hey §a{username}§7, Ti ricordiamo di seguirci su tutti i nostri_  §7social media per rimanere aggiornato sugli eventi e_  §7le novità del server!__